import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';
import { clsx } from 'clsx';
import { Inter } from 'next/font/google';

import { SiteFooter, SiteHeader } from '@/components';

const inter = Inter({ display: 'swap', subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="cs">
    <body
      className={clsx(
        'bg-noise flex min-h-svh flex-col overflow-x-hidden overflow-y-scroll overscroll-none',
        'bg-gray-50 text-gray-900 antialiased',
        inter.className,
      )}
    >
      <SiteHeader />
      <main className="flex-1 pt-14">{children}</main>
      <SiteFooter />
    </body>
  </html>
);

export default RootLayout;
